#micronaut:
#  server:
#    port: 8082

micronaut:
  server:
    cors:
      enabled: true



datasources:
  default:
    url: "jdbc:postgresql://localhost:5234/postgres"
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"

jpa:
  default:
    entity-scan:
      packages: 'recsys'